source = $HOME/.config/hypr/mocha.conf

exec = ~/.config/hypr/scripts/hyprlock-weather.sh &

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrainsMono Nerd Font

# GENERAL
general {
  hide_cursor = true
  grace = 1
  ignore_empty_input = true
  fail_timeout = 500
}

animation {
  enabled = true
  bezier = smooth, 0.4, 0.0, 0.2, 1.0
  animation = fadeIn, 1, 5, smooth
  animation_out = fadeOut, 1, 5, smooth
}

# BACKGROUND
background {
  monitor =
  path = /home/mimisriz/Downloads/lorenzo-herrera-p0j-mE6mGo4-unsplash.jpg
  blur_passes = 3
  color = $base
}

label {
  monitor =
  text = cmd[update:30000] cat ~/.cache/hyprlock_weather.txt 2>/dev/null || echo "☁️ Weather Unavailable"
  color = $mauve
  font_size = 24
  font_family = $font
  position = 30, 260
  halign = left
  valign = bottom
}


# TIME
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 90
  font_family = $font
  position = 30, 90
  halign = left
  valign = bottom
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 25
  font_family = $font
  position = 30, 60
  halign = left
  valign = bottom
}

# WELCOME MESSAGE
label {
  monitor =
  text = cmd[update:60000] echo "<i>Good $(if [ $(date +%H) -lt 12 ]; then echo morning; elif [ $(date +%H) -lt 18 ]; then echo afternoon; else echo evening; fi),</i> <b>$USER</b>"
  color = $pink
  font_size = 28
  font_family = $font
  halign = center
  valign = center
  position = 0, -120
}

input-field {
  monitor = 
  size = 200, 200                  # Bigger, circular shape
  outline_thickness = 30           # Thicker border
  dots_size = 0.3
  dots_spacing = 0.25
  dots_center = true
  outer_color = transparent
  check_color = $teal
  inner_color = rgba(0, 0, 0, 0)     # Transparent inner area
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span font="64">🔑</span>
  hide_input = true
  fail_color = $red
  fail_text = <span font="64">🔒</span> 
  capslock_color = $yellow
  position = 0, 60
  halign = center
  valign = center
  check_on_submit = true
  shadow_passed_color = $accent
  shadow_failed_color = $red
  shadow_blur = 10
}

}

label {
    monitor =
    text = cmd[update:30000] echo "🔋 $(cat /sys/class/power_supply/BAT*/capacity)% $(if [ "$(cat /sys/class/power_supply/BAT*/status)" = "Charging" ]; then echo "⚡"; fi)"
    color = rgba(255, 255, 255, 1.0)
    font_size = 28
    font_family = JetBrains Mono Bold
    position = -30, -30
    halign = right
    valign = top
}
